### ISSUE TITLE
最后运行run.cmd闪退？

### ISSUE THREAD

**Issue by lewisbatmanarnold** [hoothin/imgCodeCheck#1]
python3 deCodeImg.py -i D:\codeimg.png运行这个代码之后没有反应？

最后右键用管理员运行 run.cmd立刻闪退，这个对不对？

“用在[【邀请码助手】](https://chrome.google.com/webstore/detail/register-invitation-code/ndmlflmkmohjoechiepcpflbljadmemp)上时运行 run.cmd 启动服务后填入 http://127.0.0.1:416/?img= 即可”这个操作能否详细解释下？

**Comment by hoothin** [comment]
你安装python3和依赖库了吗？
如果实在搞不定可以尝试去买阿里云的图片识别api使用，花不了多少钱的
